### ISSUE TITLE
Double letters being removed

### ISSUE THREAD

**Issue by Janice80** [planningalerts-scrapers/coffs_harbour#6]
Hi There,

[Sorry i put this on another thread but maybe it should live here.]

I have noticed on the site that when there is a name with double letters one of the letters is removed - for example a search for Woolgoolga shows the location as "Wolgolga" and the road Crabbee as "Crabe".

I have only conducted searches for DAs in the Coffs Harbour LGA so am not sure is this is affecting other locations.

Many thanks if you could have a look at it.

Jan

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gepx)

**Comment by LoveMyData** [comment]
Nice spotting Jan, checking the code now

**Comment by Janice80** [comment]
It’s still not working for me:

https://www.planningalerts.org.au/?q=15+Woolgoolga+Creek+Road%2C+Woolgoolga+NSW

the results show Wolgolga instead of Woolgoolga and Street in the results only has one ‘e’

[cid:image001.png@01D43AC3.C17326D0]

Jan Rooney | Communications Officer
| Coffs Harbour City Council P: 02 6648 4091 | E: jan.rooney@chcc.nsw.gov.au<mailto:jan.rooney@chcc.nsw.gov.au>  | W: www.coffsharbour.nsw.gov.au<http://www.coffsharbour.nsw.gov.au>
To keep up-to-date with council news and community events please subscribe to our social media and e-newsletter services at www.coffsharbour.nsw.gov.au/subscribenow<http://www.coffsharbour.nsw.gov.au/subscribenow>
[Council logo]
This email (including any attachments) is intended only for the use of the individual or entity named above and may contain information that is confidential, proprietary or privileged. If you are not the intended recipient, please notify Council immediately by return email and then delete the email, destroy any printed copy and do not disclose or use the information in it. Coffs Harbour City Council advises that this email and any attached files should be scanned to detect viruses and accepts no liability for loss or damage (whether caused by negligence or not) resulting from the use of any attached files.

**Comment by LoveMyData** [comment]
@jamezpolley, I have adjusted the source code and this is pending PR and it will fix the data moving forward, any suggestion on how to fix the data already in PA.

**Comment by Janice80** [comment]
Sorry this is still not working, these are new listings:

https://www.planningalerts.org.au/?q=Sawtell+Road%2C+Toormina+NSW

and still missing the second letter (see the words: street, Toormina, Boambee, Coffs, Sawtell .....)

**Comment by jamezpolley** [comment]
Hi Janice and @LoveMyData 

I've merged the outstanding PR so that this should stop being an issue for data we import fresh from tomorrow.

Fixing the existing data though... 

The best idea I've got at the moment is to compare the data from https://morph.io/lovemydata/coffs_harbour with data from https://morph.io/planningalerts-scrapers/coffs_harbour. We should be able to match entries based on the council_reference, then do a diff on the address and description fields to look for changes that involve duplicating a letter, and then maybe apply those diffs to the prod DB..

**Comment by jamezpolley** [comment]
Thanks for following up Janice :)

Eric's patch hadn't been merged; it had been waiting for us to talk about how to fix the data that's already been imported. But I've realised now that that's a mistake, so I've just merged it.

I've run the scraper again, and https://www.planningalerts.org.au/authorities/coffs_harbour/applications now shows 3 more listings - including https://www.planningalerts.org.au/applications/1094258 ("Coffs Harbours" instead of "Cofs") and https://www.planningalerts.org.au/applications/1094259 ("Bonville" instead of "Bonvile")

So we shouldn't see any more broken data in future.

We still have to go back and fix the data we've already broken though. I've reopened this issue so we can tackle that.

> Sorry this is still not working, these are new listings:
> 
> https://www.planningalerts.org.au/?q=Sawtell+Road%2C+Toormina+NSW
> 
> and still missing the second letter (see the words: street, Toormina, Boambee, Coffs, Sawtell .....)

**Comment by LoveMyData** [comment]
@jamezpolley - i think this issue should be consider fixed and open a new ticket in PA to see how to modify existing data that is already in PA.
The scraper itself is no longer causing the issue.
Thoughts?

**Comment by LoveMyData** [comment]
Oh, just noted PA's issue https://github.com/openaustralia/planningalerts/issues/1272 is already closed

**Comment by jamezpolley** [comment]
> @jamezpolley - i think this issue should be consider fixed and open a new ticket in PA to see how to modify existing data that is already in PA.
> The scraper itself is no longer causing the issue.

I agree. I'll close this now and raise a different issue in PA
